dependencies:
- alias: expose
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- alias: cleanup
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- name: mynode23
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
- name: nodey24
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.3
- name: nodey26
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
